### ISSUE TITLE
Encoder Bootstrapping

### ISSUE THREAD

**Issue by gchilingaryan** [yuval-alaluf/restyle-encoder#17]
Hi @yuval-alaluf,

Thanks for your awesome project! I have a small question about the encoder bootstrapping.

I have a pre-trained StyleGAN2 model trained on FFHQ with 256x256 output resolution and fine-tuned on an anime dataset. Now, I am trying to train a ReStyle model from scratch using this model and I also used a FFHQ dataset with 256x256 resolution images for training and testing. Am I doing everything right, no anime dataset is needed for the training, only the pre-trained model and a dataset with real images?

Looking forward to your soonest answer!

**Comment by yuval-alaluf** [comment]
Hi @gchilingaryan 
You are correct. You need to train a model that is able to translate real face images to anime face images. Doing so would be best if you had paired data of real and anime, but as this is probably not the case, you can try training the encoder using only real images (similar to what I did with the toonify). Now, I can't say in advance if what I used to train the toonify task will work for you out of the box, so you may need to play around with it a bit. 
However, once you have the real-to-anime model, you can pair it with the ffhq encoder and perform the bootstrapping technique

**Comment by gchilingaryan** [comment]
The thing is when training the ReStyle model, the average anime image is note changing that much during the training (only the background of the image, the hair color and skin tone is changing depending on the input image, but the image is overall the same throughout the training). Is this a normal behaviour, did you have the same results when training the Toonify model?

**Comment by yuval-alaluf** [comment]
You should see changes beyond just changes to hair color and skin tone. You may need to play around with the losses. 
As I also mentioned, what worked for toonify may not work for anime. You may need to go beyond what was done for toonify, but the idea should be similar.

**Comment by gchilingaryan** [comment]
Alright! Thanks for your insights, I will try playing with the losses as you suggested.
