### ISSUE TITLE
when run inference_iterative.py，Nothing happens when running  On local computer

### ISSUE THREAD

**Issue by zhanghongyong123456** [yuval-alaluf/restyle-encoder#19]
![image](https://user-images.githubusercontent.com/48466610/119992203-de77f780-bffc-11eb-8e98-b92eb268e49b.png)
Nothing happens when running，On local computer，I what to know why

**Comment by yuval-alaluf** [comment]
Hi @zhanghongyong123456 
You'll need to provide me with some more details for me to help. 
What command are you running? What environment are you running from? etc.

**Comment by zhanghongyong123456** [comment]
![image](https://user-images.githubusercontent.com/48466610/120048820-ca5ae700-c04a-11eb-95af-859df5e88d0b.png)
i am runing on ubuntu18.04(super 2060(8G)) ,When I run it, nothing happens. Later I found that there was a problem with loading psp and e4e. I don’t know why this happens
![image](https://user-images.githubusercontent.com/48466610/120049025-540ab480-c04b-11eb-911e-e2ece004150e.png)
need to download models when loading psp and e4e codes?

**Comment by yuval-alaluf** [comment]
This issue is not related to downloading the models. 
However, I have a hunch of what the problem is and it is almost certainly related to the compilation of ninja.
Can you please try running the script, then pressing ctrl+c to stop the execution (or the stop command in Pycharm), and send the stack trace?

**Comment by zhanghongyong123456** [comment]
> This issue is not related to downloading the models.
> However, I have a hunch of what the problem is and it is almost certainly related to the compilation of ninja.
> Can you please try running the script, then pressing ctrl+c to stop the execution (or the stop command in Pycharm), and send the stack trace?

According to your suggestion, get the following feedback，
![image](https://user-images.githubusercontent.com/48466610/120061075-01062100-c08e-11eb-9744-5d62e8158ccc.png)

**Comment by yuval-alaluf** [comment]
Great! What I expected. 
This sometimes occurs with ninja where the compilation process is locked by a process. 
To fix this, try looking at the paths:
```
~/.cache/torch_extensions/fused/
~/.cache/torch_extensions/upfirdn2d/
```
(Or wherever your cache for the torch extensions is)

There, see if you have a file that ends with .lock or something like that. If so, delete the file and try re-running the script.
It may not necessarily be in the exact path I noted above. Can you try to find it using

```find / -name "torch_extensions"```

Please let me know if you still have trouble locating the lock file.

P.S. If this happens again, you can know that this is your problem since part of the stack trace contains the commands
```
baton.wait()
time.sleep(self.wait_seconds)
```

**Comment by zhanghongyong123456** [comment]
> Great! What I expected.
> This sometimes occurs with ninja where the compilation process is locked by a process.
> To fix this, try looking at the paths:
> 
> ```
> ~/.cache/torch_extensions/fused/
> ~/.cache/torch_extensions/upfirdn2d/
> ```
> 
> (Or wherever your cache for the torch extensions is)
> 
> There, see if you have a file that ends with .lock or something like that. If so, delete the file and try re-running the script.
> It may not necessarily be in the exact path I noted above. Can you try to find it using
> 
> `find / -name "torch_extensions"`
> 
> Please let me know if you still have trouble locating the lock file.
> 
> P.S. If this happens again, you can know that this is your problem since part of the stack trace contains the commands
> 
> ```
> baton.wait()
> time.sleep(self.wait_seconds)
> ```
Because of this problem, I can run after deleting the cache，
![image](https://user-images.githubusercontent.com/48466610/120061440-df0d9e00-c08f-11eb-95c8-d31bca97ca89.png)


Thank you very much for your reply

**Comment by zhanghongyong123456** [comment]
I want to know under what circumstances will this happen

**Comment by yuval-alaluf** [comment]
> I want to know under what circumstances will this happen

I wish I knew myself, but this `lock` is not really in my control. I am not really sure what forum you can ask this question to get a clearer answer. 

Does this solve your issue though? Are you now able to perform inference?

**Comment by zhanghongyong123456** [comment]
> > I want to know under what circumstances will this happen
> 
> I wish I knew myself, but this `lock` is not really in my control. I am not really sure what forum you can ask this question to get a clearer answer.
> 
> Does this solve your issue though? Are you now able to perform inference?

Yes, it's working now, But I'm not sure when this lock will be wrong and won't work
