### ISSUE TITLE
How to apply a single encoding iteration

### ISSUE THREAD

**Issue by SelfishGene** [yuval-alaluf/restyle-encoder#2]
Hi, thanks for the very diligent work all you guys are doing in the lab

I'm a little bit confused by all the various wrapping functions and the many flags in the forward pass of the psp and e4e models ("input_code", "latent", etc.).

If my goal is to simply apply a single iteration of the encoder by sending it a target image and a current guess image (and nothing else) and receive as output the w offset that is needed to slightly make the next guess better (and nothing else). 
i.e. something like:

`delta_w = encoder_single_iteration(I_target, I_curr_estimate)
`  

How should that function look like? 
For simplicity let's assume both images have already underwent the appropriate "img_transforms" and are torch tensors of shape (3,256,256)

I believe this simpler interface to the encoder/refiner might also be useful for other researchers, so perhaps worth having an example in the notebook?

Thanks again for all the good work!

**Comment by yuval-alaluf** [comment]
Hi @SelfishGene ,

I agree that although there are a lot of arguments to the `forward()` function of pSp and e4e, most of the values remain with their defaults. A general inference call will look like: 
```python
net.forward(x_input, latent=latent, randomize_noise=False, return_latents=True, resize=opts.resize_outputs)
```
where `x_input` is the 6-channel input and `latent` is the current latent guess. The rest will pretty much always stay as is. 
 
To find the deltas learned at each step, how will a typical flow look like?

```python
# assume we have loaded the `net` and the transformed image, `I_target`
...
 # get the average image for initialization
avg_image = get_avg_image(net) 
# run inference
result_batch, result_latents = run_on_batch(I_target.unsqueeze(0).cuda(), net, opts, avg_image)
# since you're working on a batch with one image, get the first output
# `image_latents` holds all the latents obtained in each inference step. 
image_latents = result_latents[0]
# get the deltas learned between each inference step
deltas = [image_latents[i] - image_latents[i-1] for i in range(1, opts. n_iters_per_batch + 1)]
```

My goal with the current interface was to allow one to easily extract (1) the intermediate images and (2) intermediate latents. And with these intermediate outputs, one can extract the deltas with a single line of code. 
 
I hope this helps clarify your question, but let me know if something is still unclear.

**Comment by SelfishGene** [comment]
Yes, thank you @yuval-alaluf
