### ISSUE TITLE
Generate the image according to the latent code

### ISSUE THREAD

**Issue by zhanghongyong123456** [yuval-alaluf/restyle-encoder#22]
Hello, after I realize the latent code editing, I want to get the edited image. I would like to ask whether it can be achieved by using this code. I would like to ask what my latent code format should be like.My current latent code format is (1, 18, 512) shape, numpy.ndarray, looking forward to your reply
![104](https://user-images.githubusercontent.com/48466610/122223100-745cbf00-cee5-11eb-94d5-1e777077a643.png)
my code about Generate image by latent code，I do the latent code editing based on StyleGan2

**Comment by yuval-alaluf** [comment]
Hi @zhanghongyong123456 
I believe the code looks good and I believe the shape (1, 18, 515) is correct. Did you try running the code? Did you get an error or an unexpected result?

**Comment by zhanghongyong123456** [comment]
> Hi @zhanghongyong123456
> I believe the code looks good and I believe the shape (1, 18, 515) is correct. Did you try running the code? Did you get an error or an unexpected result?

I run ，get this error ，
![107](https://user-images.githubusercontent.com/48466610/122313760-5e80e580-cf49-11eb-9ff6-e39c16697c2a.png)
![106](https://user-images.githubusercontent.com/48466610/122313764-604aa900-cf49-11eb-886e-464441d2b846.png)
![105](https://user-images.githubusercontent.com/48466610/122313767-60e33f80-cf49-11eb-9814-8d8d1f5f9b04.png)

**Comment by yuval-alaluf** [comment]
Try changing the numpy array to a torch tensor using `torch.from_numpy`

**Comment by zhanghongyong123456** [comment]
> Try changing the numpy array to a torch tensor using `torch.from_numpy`

I'm sorry to bother you again. I used your method, but there were other mistakes. I don't know much about the internal implementation of your code, so I don't know how to solve it
![1101](https://user-images.githubusercontent.com/48466610/122341392-014f5900-cf76-11eb-8e6d-7e8f00c3d27a.png)
![109](https://user-images.githubusercontent.com/48466610/122341400-03191c80-cf76-11eb-9931-c3b2cb11988d.png)
![108](https://user-images.githubusercontent.com/48466610/122341403-03b1b300-cf76-11eb-887b-7a01067dd4be.png)

**Comment by yuval-alaluf** [comment]
Hard to pin point exactly what the issue is because you're getting an unknown CUDA error, but I believe when calling the decoder you still want to wrap `latent` in a list.

**Comment by zhanghongyong123456** [comment]
> Hard to pin point exactly what the issue is because you're getting an unknown CUDA error, but I believe when calling the decoder you still want to wrap `latent` in a list.

Could you please provide a code or a hidden code format to generate a single image? Now I don't know if there is something wrong with the hidden code I made or the environment I configured，My environment is the conda virtual environment, cudatookit=10.1, is that OK

**Comment by zhanghongyong123456** [comment]
> Hard to pin point exactly what the issue is because you're getting an unknown CUDA error, but I believe when calling the decoder you still want to wrap `latent` in a list.

When I add Latent. Unsqueeze (0) and Net.Decoder ([latent],.., I got the following error and I'm wondering if this is the problem here
![1012](https://user-images.githubusercontent.com/48466610/122369395-bbec5500-cf90-11eb-8c64-9c276987492c.png)
![1011](https://user-images.githubusercontent.com/48466610/122369402-bdb61880-cf90-11eb-8635-7a7525f9bf5a.png)
![1010](https://user-images.githubusercontent.com/48466610/122369404-be4eaf00-cf90-11eb-8d7f-0dfa65e29911.png)

**Comment by yuval-alaluf** [comment]
Seems like you need to move the latent to the gpu using `.cuda()`

**Comment by zhanghongyong123456** [comment]
> Seems like you need to move the latent to the gpu using `.cuda()`

Yes, he's working normally.Thank you very much
