### ISSUE TITLE
not an issue - were any efforts made / investigated into using this with video?

### ISSUE THREAD

**Issue by johndpope** [yuval-alaluf/restyle-encoder#24]
I want to swap out faces and replace them different ones in a video.![image](https://user-images.githubusercontent.com/289994/124352809-1a2e5e80-dc46-11eb-9612-776d116cd522.png)
Are you familiar with any ways this could be done / with high quality?

I'm familiar with fsgan - https://github.com/YuvalNirkin/fsgan  but not sure how to go about the neural net surgery

**Comment by yuval-alaluf** [comment]
I am a bit unfamiliar with reenactment works so it is hard for me to say off-hand. However, I think one of the challenges will be the difference in the format of the images inputted to ReStyle and the format of the images used in FSGAN. What I mean by this is that ReStyle relies on StyleGAN which pre-aligns the images while it seems like FSGAN can work on images in-the-wild so this is something you may need to take into consideration.

**Comment by johndpope** [comment]
FSGAN possibly superceded https://github.com/neuralchen/SimSwap
when running fsgan - it crops images into squares with alignment.

**Comment by yuval-alaluf** [comment]
I see. So I guess pSp or ReStyle could work here, but its a bit hard for me to say how much work it would be to get it to work well. I guess the best way to find out is to try 😄
