### ISSUE TITLE
Target path?

### ISSUE THREAD

**Issue by GLivshits** [yuval-alaluf/restyle-encoder#25]
Hello. I wonder what does y variable means in the Coach as well as what is the target path for Dataloader.

**Comment by yuval-alaluf** [comment]
The y variable denotes the target image while the target path denotes the path to the directory holding the target images. For the inversion task the target image is equal to the source image and so `x=y`. 
The reason for this distinction is in case you wish to perform image to image translation in which the source and target images are different.
