### ISSUE TITLE
错误  错误  error

### ISSUE THREAD

**Issue by dingyan1478** [yuval-alaluf/restyle-encoder#3]
Why did I make this mistake？
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by yuval-alaluf** [comment]
Hi @dingyan1478,
Can you please provide some more information on what you're trying to run and on your environment?

**Comment by dingyan1478** [comment]
Hi!
I want to use the network to train my data sets, which are underwater data sets, clear underwater images and color biased underwater images. My server has some problems recently, so I use the windows system's Pytorch to run. I don't know if it's the system's reason. I've changed the path of the data sets.
Thank you!

**Comment by yuval-alaluf** [comment]
We haven't tested the code on windows, but it should work if you configure your environment correctly and have correct CUDA configurations. 
I searched the error you got and found this thread that could be useful: https://github.com/HRNet/HRNet-Semantic-Segmentation/issues/39
Regarding running on windows, this may be useful: https://github.com/eladrich/pixel2style2pixel/issues/29
