### ISSUE TITLE
Problem with importing dlib

### ISSUE THREAD

**Issue by denabazazian** [yuval-alaluf/restyle-encoder#34]
I have problem with installing dlib. It seems that dlib is incompatible with other packages of this repository (pytorch and cuda). 
When I try to install dlib with `pip install dlib`, I get this error: 

>`ERROR: Failed building wheel for dlib`

I have also tried different conda installation for dlib, such as: ` conda install -c conda-forge dlib ` , ` conda install -c menpo dlib ` , ` conda install -c conda-forge/label/cf201901 dlib ` , ` conda install -c conda-forge/label/cf202003 dlib ` , but I get the following error: 

> `Output in format: Requested package -> Available versions
The following specifications were found to be incompatible with your system:
 feature:/linux-64::__glibc==2.17=0
 feature:|@/linux-64::__glibc==2.17=0
 Your installed version is: 2.17`

I created a clean conda environment and right after installing python, I could easily install dlib with conda and I could import it correctly, but then I couldn't install pytorch, there were some incompatible packages. If I first install pytorch, then I cannot install dlib, and if I first install dlib, then I cannot install pytorch. The command that I use for installing pytorch is:

>`conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch`

The other packages that I use are: `python=3.6`, `GCC 7.3.0`, `libgcc-ng=7.3`, `regex-2018.11.22`, `tqdm-4.62.2`, `ftfy-5.3.0`, `matplotlib-2.2.2`, `numpy-1.15.2`.  The conflict just happens between pytorch and dlib installations.

The installation of dlib doesn't exist in the conda environment [link](https://github.com/yuval-alaluf/restyle-encoder/blob/main/environment/restyle_env.yaml) of this repository. In this [code](https://github.com/yuval-alaluf/restyle-encoder/blob/main/scripts/align_faces_parallel.py) you explained the dlib installation separately. I'm wondering whether you used a different environment for that code or you have experienced the same error for installing dlib and pytorch in a same conda environment. 

Thanks for sharing your fantastic work.

**Comment by yuval-alaluf** [comment]
Hi @denabazazian 
I haven't come across issues with the installation of `dlib`. Were you unable to install it correctly by using the steps specified in the script you linked above within the conda environment?
I was able to install it using the `conda` environment I linked to this repo, but this was a while back. So if you are still unable to install it in the conda environment of the repo using the steps in the script I will try creating a clean environment to try to recreate the error.

**Comment by denabazazian** [comment]
Many thanks @yuval-alaluf for your reply. 
I made another clean conda environment by the link in this repo (`conda env create -f restyle_env.yaml`). I could install `dlib` by running `conda install -c conda-forge/label/cf202003 dlib` right after creating the environment (I couldn't install `dlib` with `pip`). But, the problem is that `cudatoolkit` is not installed in the `conda` environment of this [repo](https://github.com/yuval-alaluf/restyle-encoder/blob/main/environment/restyle_env.yaml), therefore it is not possible to import pytorch with `cuda`. Hence, when I install pytorch with `cudatoolkit=10.1`, that incompatibility with `dlib` appears. 
I searched more about this issue and based on this [reference](http://dlib.net/release_notes.html), it seems that `dlib 19.17` is compatible with `cuda 10.1` , but there is no conda installation for this specific version of `dlib`, and I cannot install `dlib` with `pip`, I get this error: `ERROR: Failed building wheel for dlib` every time.

**Comment by yuval-alaluf** [comment]
Hi @denabazazian
Sorry for the late reply. I just had a chance to create a new environment using `conda env create -f restyle_env.yaml` just like you did. 
Then, I was able to install `dlib` using `pip install dlib==19.21.1`, but I am using `cuda 11.1` on `Ubuntu 18.04.5`. 
I am wondering if this is a problem with different CUDA versions?

**Comment by denabazazian** [comment]
Hi @yuval-alaluf , thanks a lot for your reply and your effort for re-creating the environment. 
I am using `Cuda 10.1` on `CentOS 8`. I believe, CUDA versions caused the problem. At the end, the only solution for my case was to run the `align_face` in a different environment with `dlib`, and saved the outputs locally. Then, load them with the main environment of `restyle` repository to complete the process.

**Comment by yuval-alaluf** [comment]
Hmm. Not ideal but I guess it's a decent workaround. I'll try to look into `dlib` a bit more later to see if there is anything that can help. 
For now I'm closing the issue, but I'll update you if I find anything useful.

**Comment by AwesomeLemon** [comment]
I had the same issue with ``dlib``, the solution was ``conda install -c conda-forge dlib`` - this worked while ``pip install`` (and ``pip install dlib==19.21.1``) failed. Leaving this comment here in case anyone else faces this issue.
