### ISSUE TITLE
 It doesn't work.

### ISSUE THREAD

**Issue by scj0709** [yuval-alaluf/restyle-encoder#35]
Hi!
I entered the training code, but nothing happens.
When stopped, the following message appears:
![image](https://user-images.githubusercontent.com/40060713/132470373-9d54b2cd-2ceb-42e3-abc1-9e8bdc2d9951.png)

**Comment by yuval-alaluf** [comment]
Hi @scj0709 ,
Have a look at my comments in the following issue: https://github.com/yuval-alaluf/restyle-encoder/issues/31
I think it may help solve your issue :)
