### ISSUE TITLE
I would like to ask the author, have you trained latensts that can change age or expression, just like the 23 vectors provided by stygan2 encoder? I found that their vectors do not fit this project?

### ISSUE THREAD

**Issue by tianjialiang12** [yuval-alaluf/restyle-encoder#36]

**Comment by yuval-alaluf** [comment]
Yes, you can do latent space manipulation with the directions for controlling age, expression, etc. 
Although this repo doesn't have the code for performing the edits you can run the `inference_iterative.py` script to save the inverted latents for your images. 
Then, you can head over to the [encoder4editing](https://github.com/omertov/encoder4editing/tree/main/editings) repo where there you can find several StyleGAN2 directions and a `LatentEditor` class that can be used for performing edits using InterFaceGAN, GANSpace, and SeFA. 
I get a chance within the next couple of weeks I will add support for latent space editing directly in this repo so there's no need to jump over to a different repo.

**Comment by yuval-alaluf** [comment]
Hi, I just added support for running InterFaceGAN on the inversion of ReStyle. Please take a look at the following for more details: https://github.com/yuval-alaluf/restyle-encoder#editing
The provided script will run inversion and edit in a single script so there is no need to use multiple scripts or move over to a different repo. 
For now I am closing this issue as the commit answers your question :)
