### ISSUE TITLE
Can we reduce the trained model size?

### ISSUE THREAD

**Issue by Zeeshan75** [yuval-alaluf/restyle-encoder#39]
Hi @yuval-alaluf 

I have worked with your code and models and the results are good. Is there any way we can reduce the trained model size?

**Comment by Zeeshan75** [comment]
I tried to convert using ONNX but I'm stuck with the actual input passed after loading the model architecture.


```
model_path = '/content/restyle-encoder/pretrained_models/restyle_psp_ffhq_encode.pt'
ckpt = torch.load(model_path, map_location='cpu')
opts = ckpt['opts']
opts['checkpoint_path'] = model_path
opts['device'] = 'cpu'
opts = Namespace(**opts)
net = pSp(opts)    
net.eval()
net.cpu()
```

**I am able to load the model successfully**. 
Later while passing the input to the model the actual inputs are different when compared to the random input.

I have followed the [referece](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)

```
x = torch.randn(batch_size, 1, 224, 224, requires_grad=True) # input our model is expecting is [64, 6, 3, 3]
torch_out = net(x)
```
I replaced the values to generate random input and when I passed to the **net(x)** facing the memory issue.

**Comment by yuval-alaluf** [comment]
> How can we reduce the model size?

When you mean reduce the model size, are you referring to reducing the number of parameters in the network itself? 
If so, you may notice that most of the weights of the encoder are actually contained in the `map2style` blocks (https://github.com/yuval-alaluf/restyle-encoder/blob/main/models/encoders/map2style.py). You'll notice that these blocks are simply 4 layers of convolutions.  What you could do is possibly reduce the number of convolutions by doing `conv-maxpool-conv-max-pool`. Another option is to increase the shared backbone of the encoder. Currently, the shared backbone outputs a feature maps of `16x16x512` followed by `18` separate heads. What you could do is have the shared backbone output something like `8x8x256` or something. Yet another option is to figure out how you can reduce the number of heads. Perhaps there is a clever "merging" you could do between some of the heads. 

> How can I convert it to ONNX? 

I am a bit unfamiliar with ONNX so I may have a hard time assisting you here. Can you provide more details as to the error you're getting after you converted the model? Maybe with more details I can try helping you out some more :)

**Comment by Zeeshan75** [comment]
Hi again!

Thanks for the reply.

I will try to implement the above mentioned techniques.

Here is the below error when I tried to convert the model to ONNX.

**RuntimeError: Exporting the operator prim_layout to ONNX opset version 10 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.**

**Comment by yuval-alaluf** [comment]
Regarding the error, I have never used ONNX so I am not really sure what the error refers to. Maybe you can find a more helpful solution on other forums related more to ONNX.
