### ISSUE TITLE
Dataset Horses and Churches for training and testing. 

### ISSUE THREAD

**Issue by di-mi-ta** [yuval-alaluf/restyle-encoder#47]
Hi, 

I see in the paper, you prepare for the training and testing set of Horses dataset as follows: 

- Horses: From the LSUN Horse dataset, we randomly select 10,000 images to be used for training and 2,215 images used for evaluations.

So, could you release these image ids or image filenames of these sampled images for the reproducing purpose?

Thanks!

**Comment by yuval-alaluf** [comment]
Unfortunately, it seems like the image names we have stored in our system were modified when saved. Therefore, providing the list of file names will not be able to help you. 
And I believe that due to licensing, I am unable to upload the actual images used for training/evaluation.
