### ISSUE TITLE
how to interpolate latents?

### ISSUE THREAD

**Issue by molo32** [yuval-alaluf/restyle-encoder#5]
how to interpolate latents.

If I have two latents, how do I interpolate them? to have an intermediate face.

**Comment by yuval-alaluf** [comment]
To interpolate two latents, you could perform the following flow: 
```python
def interpolate_latents(latent1, latent2, ratio):
    return latent1 + ratio * (latent2 - latent1)

def interpolate(src_latent, target_latent, n_interpolations=10):
    """
    Generate interpolation results between src_latent and target_latent
    """
    # convert the latents to shape [1, k, 512]
    src_latent, target_latent = src_latent.unsqueeze(0), target_latent.unsqueeze(0)
    # generate source and target images images
    src_img = net.decoder([src_latent], input_is_latent=True, randomize_noise=False)
    target_img = net.decoder([target_latent], input_is_latent=True, randomize_noise=False)
    # generate interpolation images
    results = [src_img]
    for i in range(1, n_interpolations+1):
            interpolation_ratio = i / (n_interpolations+1)
            inter_code = interpolate_latents(src_latent, target_latent, interpolation_ratio)
            image, _ = net.decoder([inter_code], randomize_noise=False, input_is_latent=True)
            results.append(image)
    results.append(target_image)
    return torch.cat(results)
```
If you take the results of `interpolate` and visualize them, you should see the interpolated images.  
Please note I wrote this code just now without running it so I probably missed some things so it will probably not work as is but the idea is here.

**Comment by zhanghongyong123456** [comment]
> To interpolate two latents, you could perform the following flow:
> 
> ```python
> def interpolate_latents(latent1, latent2, ratio):
>     return latent1 + ratio * (latent2 - latent1)
> 
> def interpolate(src_latent, target_latent, n_interpolations=10):
>     """
>     Generate interpolation results between src_latent and target_latent
>     """
>     # convert the latents to shape [1, k, 512]
>     src_latent, target_latent = src_latent.unsqueeze(0), target_latent.unsqueeze(0)
>     # generate source and target images images
>     src_img = net.decoder([src_latent], input_is_latent=True, randomize_noise=False)
>     target_img = net.decoder([target_latent], input_is_latent=True, randomize_noise=False)
>     # generate interpolation images
>     results = [src_img]
>     for i in range(1, n_interpolations+1):
>             interpolation_ratio = i / (n_interpolations+1)
>             inter_code = interpolate_latents(src_latent, target_latent, interpolation_ratio)
>             image, _ = net.decoder([inter_code], randomize_noise=False, input_is_latent=True)
>             results.append(image)
>     results.append(target_image)
>     return torch.cat(results)
> ```
> 
> If you take the results of `interpolate` and visualize them, you should see the interpolated images.
> Please note I wrote this code just now without running it so I probably missed some things so it will probably not work as is but the idea is here.

Hello, after I realize the latent code editing, I want to get the edited image. I would like to ask whether it can be achieved by using this code. I would like to ask what my latent code format should be like.My current latent code format is (1, 18, 512) shape, numpy.ndarray, looking forward to your reply

**Comment by zhanghongyong123456** [comment]
![104](https://user-images.githubusercontent.com/48466610/122189052-2cc53b80-cec3-11eb-9c02-c070f072a654.png)
my code  about Generate image by  latent code
