### ISSUE TITLE
The model collapse when use moco loss

### ISSUE THREAD

**Issue by tommy-qichang** [yuval-alaluf/restyle-encoder#50]
Hi Yuval,

When I train my datasets with the configuration you recommended, the model seems to collapse after just a few iterations(As shown below). However, when I set the moco lambda as 0.0001, there is no problem so far. So do you have any clue why that happens? Is there a way to disable the moco loss totally? (when I set the moco loss as 0, it seems you bind the id_logs with the moco_loss calculation)

![image](https://user-images.githubusercontent.com/19438484/139087616-dbafc4b2-a2bc-4c91-84b4-81b813ea2a89.png)

**Comment by feddgannature** [comment]
I just use l2 and lpips loss. And I've tried using id loss, which shows a comparable result. But when I add moco loss, the synthetic image starts to become worse. I'm not sure why, but I'll keep my eyes on the problem. Thank you.

**Comment by tommy-qichang** [comment]
I just use l2 and lpips loss. And I've tried using id loss, which shows a comparable result. But when I add moco loss, the synthetic image starts to become worse. I'm not sure why, but I'll keep my eyes on the problem. Thank you.

**Comment by yuval-alaluf** [comment]
It does make some sense that the moco loss may lead to unsatisfactory results because MoCo was pretrained on ImageNet which is quite different from your data. Have you tried disabling the moco loss by setting the lambda value to 0?

**Comment by tommy-qichang** [comment]
Yes, I'm trying to disable Moco loss and right now the training goes well.
Thank you so much for your guidance.
