### ISSUE TITLE
Issue with loading moco pretrained model

### ISSUE THREAD

**Issue by dongyunkim-arch** [yuval-alaluf/restyle-encoder#51]
Hello!

Faced some issue when training my custom dataset with moco pretrained model. In your document, you posted moco_v2_800ep_pretrain.pt file, but the code tried to load moco_v2_800ep_pretrain.pth.tar

Not a big issue, but just in case!

**Comment by yuval-alaluf** [comment]
Yea the path in the config file is probably incorrect. 
I will take a look and correct it hopefully next week :)

**Comment by yuval-alaluf** [comment]
Fixed 😄
