### ISSUE TITLE
How many images do we need to train a restyle model?

### ISSUE THREAD

**Issue by SandroChen** [yuval-alaluf/restyle-encoder#52]
Just like the title, maybe silly but very important!

**Comment by yuval-alaluf** [comment]
It depends on the domain and data. For faces, we used all 70,000 FFHQ images. For the cars domain, we used the ~8,000 training images from Stanford Cars. It all depends on the difficulty of the domain, but the more data, the better.

**Comment by SandroChen** [comment]
Thank you! It would be helpful!

**Comment by SandroChen** [comment]
And I wonder how many epochs do you train for FFHQ? Last time I put in 4000 images and trained for 200 epochs, but the result turns out not too good.

**Comment by yuval-alaluf** [comment]
We don't measure the training, but total training steps. If I remember correctly, our models were trained for approximately 100,000 iterations.
