### ISSUE TITLE
Gender Editing

### ISSUE THREAD

**Issue by cursan-a** [yuval-alaluf/restyle-encoder#53]
Hello Yuval,

Thank you a lot for all of your work it amazing and fascinating to discover. I'm brand new in GAN universe (and even in ML universe) and i'm trying to apply gender editing on Restyle-Encoder.
Thank to your playbooks i already figured how get inference from a real picture, apply a transition between 2 inferences and lastly apply an age edition.
For my research I need now to apply a gender edition. As i understand it your project works with "ReStyle-e4e models [...] obtained via InterFaceGAN".
Can you give me some direction to succeed on my purpose ? Have I to train the `.pt` model by myself ? Is there somewhere others models already usable on Restyle ? Sorry if my question seems stupid, I'm a bit lost.

Thank you in advance !

**Comment by wiibo** [comment]
I also want to know how to get the interfacegan boundaries which dimension is (1,512), while the size of the latents is (18,512)?
Thank you in advance !

**Comment by cursan-a** [comment]
I tried something by myself : 
- I loaded the numpy model got from [interfacegan repository](https://github.com/genforce/interfacegan/blob/master/boundaries/stylegan_ffhq_gender_boundary.npy).
- Because model in ReStyle repository are Float32 typed, I converted the loaded model
- Lastly, I transformed it to a Torch model (as it was done in [latent_editor.py](https://vscode.dev/github/yuval-alaluf/restyle-encoder/blob/7f2bee3394af070b1b1bf1ddd192e751788ea635/editing/latent_editor.py))
```
md2 = np.load('./stylegan_ffhq_gender_boundary.npy')
md2 = np.float32(md2)
md2 = torch.from_numpy(md2).cuda()
```

I had no errors but results don't go as expected at all. I have no gender change at all. Only small changes on eyes.

If you have any advice, i'm interested :).

**Comment by yuval-alaluf** [comment]
Regarding the edits, you can still apply the (1, 512) dimensional-boundary on the latents that are of size (18, 512). The editing script posted in this repository will handle all of the broadcasting for you.  

> I loaded the numpy model got from interfacegan repository.
> I had no errors but results don't go as expected at all. I have no gender change at all. Only small changes on eyes.

Please note that the InterFaceGAN repository used boundaries for StyleGAN1 and they are therefore not relevant for editing images in StyleGAN2. If you wish to create a new boundary, you will need to train it yourself. 

The repository for AnyCost GAN provided a bunch of boundaries for StyleGAN2. I haven't played with it myself, but their code could be useful if you wish to edit attributes that are not provided in this repository. You can check out the script here: 
https://github.com/mit-han-lab/anycost-gan/blob/master/tools/extract_edit_directions.py

I hope this answers your questions, but if you still are unsure of something, please feel free to comment.

**Comment by cursan-a** [comment]
Hello Yuval,

Thank you so much for your answer. I succeed to do what I was trying for !
