### ISSUE TITLE
How to get a latentcode.npy file of an custom image can you help me 

### ISSUE THREAD

**Issue by abdul756** [yuval-alaluf/restyle-encoder#56]

**Comment by yuval-alaluf** [comment]
If you have a custom image, you can place the image in a directory and call `inference.py`. An example command is provided in the readme: 
```
python scripts/inference_iterative.py \
--exp_dir=/path/to/experiment \
--checkpoint_path=experiment/checkpoints/best_model.pt \
--data_path=/path/to/test_data \
--test_batch_size=4 \
--test_workers=4 \
--n_iters_per_batch=5
```
Running the above script will save the `latents.npy` is the `exp_dir` directory. 
The `data_path` should point to the directory containing your custom image and the `checkpoint_path` should point to the path containing the pre-trained ReStyle model which you can download via the links provided in the repo.

**Comment by abdul756** [comment]
> If you have a custom image, you can place the image in a directory and call `inference.py`. An example command is provided in the readme:
> 
> ```
> python scripts/inference_iterative.py \
> --exp_dir=/path/to/experiment \
> --checkpoint_path=experiment/checkpoints/best_model.pt \
> --data_path=/path/to/test_data \
> --test_batch_size=4 \
> --test_workers=4 \
> --n_iters_per_batch=5
> ```
> 
> Running the above script will save the `latents.npy` is the `exp_dir` directory. The `data_path` should point to the directory containing your custom image and the `checkpoint_path` should point to the path containing the pre-trained ReStyle model which you can download via the links provided in the repo.

thanks you a lot , I have got the latent code now i want to change the pose of the image with the latent code. Can you help me how to get pose with angle of that pose?

**Comment by yuval-alaluf** [comment]
>  I have got the latent code now i want to change the pose of the image with the latent code. Can you help me how to get pose with angle of that pose?

To change the pose of the images, you can either use the LatentEditor class provided in the repo, or run the `inference_editing.py` script. We provide the pose edit direction there. 

If you want to edit an image to get a pose at a specific target angle, this will be a bit more involved. For example, you could apply InterFaceGAN and along every step of the edit direction, you can calculate the pose angle using some predefined pose estimation model such as [HopeNet](https://github.com/natanielruiz/deep-head-pose). Then, once you get a pose that is close enough to your target angle, you can stop traversing in this direction. 
Hope this helps.
