### ISSUE TITLE
Is Conditional Image Synthesis possible?

### ISSUE THREAD

**Issue by gzhhhere** [yuval-alaluf/restyle-encoder#57]
take  the task 'Segmentation Map to Face' for example, 
get an image from the avg_latent,  
then concat with a  Segmentation Map ('lable_nc=19'), 
and get next image from decoder.

**Comment by yuval-alaluf** [comment]
Since ReStyle can be applied over something like pSp, the conditional image synthesis task should be possible with some adjustments to the code. 
It seems like the idea you propose here is the right direction.

**Comment by gzhhhere** [comment]
Ok! I see. Thank you for your reply.

**Comment by rut00** [comment]
Hello @gzhhhere, did you find any way for Conditional Image Synthesis?
If you can please share the code changes required for Conditional Image Synthesis. 

Here is the link to my original issue: https://github.com/yuval-alaluf/restyle-encoder/issues/79#issue-1355991703
