### ISSUE TITLE
Can restyle inference run purely on CPU?

### ISSUE THREAD

**Issue by jackkwok** [yuval-alaluf/restyle-encoder#58]
I notice there are a bunch of .cuda() calls in the inference_playground notebook [notebooks/inference_playground.ipynb](https://github.com/yuval-alaluf/restyle-encoder/blob/main/notebooks/inference_playground.ipynb).

Is it possible to run the whole inference using CPU?

**Comment by yuval-alaluf** [comment]
In its current state, ReStyle can't run on CPU. I think making it run on CPU will be quite difficult because StyleGAN2 relies on some specialized CUDA kernels. You can change these implementations to a native implementation in python, but getting them working will require some adjustments.

**Comment by jackkwok** [comment]
Thank you.
