### ISSUE TITLE
Pretrained model for AFHQ Cat & Dog

### ISSUE THREAD

**Issue by yingchen001** [yuval-alaluf/restyle-encoder#65]
Hi Yuval,

Thanks for sharing this impressive and interesting work. I'm wondering whether you have pretrained psp/e4e models for AFHQ Cat and Dog datasets?

Regards.

**Comment by yuval-alaluf** [comment]
Unfortunately we do not have those models available for release. They were trained on a slightly different code base and hence are incompatible with the official code.
