### ISSUE TITLE
Set training iteration steps

### ISSUE THREAD

**Issue by RahulBhalley** [yuval-alaluf/restyle-encoder#66]
Hi Yuval! Thanks for this work. 

I understand there's a flag to save training progress but on Kaggle my program crashes due to 12 hours session duration. This way my whole training progress is lost. I wanna be able to set the training iteration steps to avoid crash. How can I do that?

Regards
Rahul Bhalley

**Comment by yuval-alaluf** [comment]
If I understand what you want to do, you can save the `self.global_step` in the `state_dict` when saving. Then, when you load the checkpoint, you can set the current start step as the step saved in the `state_dict`.

**Comment by RahulBhalley** [comment]
This seems to be doable with `--resume_training_from_ckpt` and `--save_training_data` flags as in comments in your code. 

Sorry for not being able to convey my query correctly.

What I wanna do is stop training at some iteration step (which I'll find myself) so that the program doesn't crash due to 12 hours per session limit. 

For instance, if the training currently runs for a total of 70k steps but after first 12 hours only 2k steps were completed then I wanna stop training right there (just few minutes before 12 hours session duration) so that the notebook doesn't crash. Then I wanna continue training in next session using that trained checkpoint (which I think will be handled with `--resume_training_from_ckpt` and `--save_training_data` flags).

**Comment by RahulBhalley** [comment]
Thank you. Found this flag inside [train_options.py](https://github.com/yuval-alaluf/restyle-encoder/blob/main/options/train_options.py).
