### ISSUE TITLE
`resume_training_from_ckpt` vs `checkpoint_path` flag

### ISSUE THREAD

**Issue by RahulBhalley** [yuval-alaluf/restyle-encoder#68]
I set `--save_training_data` flag in `!python scripts/train_restyle_e4e.py` training execution command. Now I'm confused which one of `resume_training_from_ckpt` and `checkpoint_path` to use to continue training. 

When I set `resume_training_from_ckpt="iteration_2000.pt"`, then the output is as follows:
```
Loading encoders weights from irse50!
Loading decoder weights from pretrained path: pretrained_models/stylegan2-ffhq-config-f.pt
```

But when I set `checkpoint_path="iteration_2000.pt"`, then the output is as follows:
```
Loading ReStyle e4e from checkpoint: ../iteration_2000.pt
```

From these console outputs it seems to me that `resume_training_from_ckpt` is loading pre-trained models whereas `checkpoint_path` is loading trained `iteration_2000.pt` checkpoint. **Am I right? What should I do?**

**Update**

Using `resume_training_from_ckpt` throws error:

```
Traceback (most recent call last):
  File "scripts/train_restyle_e4e.py", line 85, in <module>
    main()
  File "scripts/train_restyle_e4e.py", line 28, in main
    coach = Coach(opts, previous_train_ckpt)
  File "./training/coach_restyle_e4e.py", line 102, in __init__
    self.load_from_train_checkpoint(prev_train_checkpoint)
  File "./training/coach_restyle_e4e.py", line 111, in load_from_train_checkpoint
    self.discriminator.load_state_dict(ckpt['discriminator_state_dict'])
KeyError: 'discriminator_state_dict'
```

**Comment by RahulBhalley** [comment]
From source code it looks like `checkpoint_path` is a way to go. Closing this issue. Anyway, would still be great to know the purpose of `resume_training_from_ckpt` flag.

Sorry for creating these many issues btw.

**Comment by yuval-alaluf** [comment]
No problem with the issues. Feel free to keep them coming :) 
Regarding the parameters, these were taken from the original encoder4editing repository and they're indeed very similar. What I usually do when I resume training is set both of them equal to the checkpoint path just to be safe. This seems to handle all the loading required.

**Comment by RahulBhalley** [comment]
> No problem with the issues. Feel free to keep them coming :)

😄😇

> What I usually do when I resume training is set both of them equal to the checkpoint path just to be safe. This seems to handle all the loading required.

That's interesting. I'ma give it a try! Thanks for replies. :)
