### ISSUE TITLE
Using restyle-encoder on a single-channel image dataset

### ISSUE THREAD

**Issue by Mo-Irene** [yuval-alaluf/restyle-encoder#69]
Hi~

I'm doing some work on a non-face domain, and I followed here from your last work psp because I noticed you said that restyle-encoder might be more suitable for that, thanks for your your progressing work！

Since my dataset is some single channel images, and I have trained my own stylegan2-ada generator, I was wondering if I could make a slight change in the code to get my work done correctly.

I noticed the following code：
https://github.com/yuval-alaluf/restyle-encoder/blob/3dacd706c79f42fc828afc0d3b05f29dd0406454/models/psp.py#L122-L127

I would be very grateful if you could give me some advice on how to modify this code. Or is there any other change I need to make?

**Comment by yuval-alaluf** [comment]
Here, we are transferring over the weights of the pretrained resnet34 network to our 6-channel encoder. In your case, I would simply omit this part and retrained the first layer from scratch. I don't think you'll see much of a difference in the performance of the network. 

Note that to get ReStyle to work on 1-channel inputs, you'll need to make some small, yet delicate changes to the code. For example, take a look at the following lines: 
https://github.com/yuval-alaluf/restyle-encoder/blob/3dacd706c79f42fc828afc0d3b05f29dd0406454/models/psp.py#L60-L67
This is the part that takes the deltas outputted in the current iteration and adds them to the previous latent code. Here, this is done only if `x.shape[1] == 6`, which is incompatible with your training scheme and hence you will never enter this `if` statement. A quick fix would probably be to change the `if` statement to check `x.shape[1] in [2,6]` but of course, this is bad coding practice :)
I think that checking `if x.shape[1] ==  self.opts.input_nc` could also work here, where `input_nc` would equal `2` in your case (if I'm not mistaken).

**Comment by Mo-Irene** [comment]
Thanks for your quick reply, I'll try it myself :)

Also, just wanted to ask you, I always get similar results when I train images, both on psp or restyle, can you suggest me some possible problems with this? Below are some sample images that I got in rsestyle-encoder after training on a very small dataset (about a few hundred images, converted to RGB and read in) with the default parameter settings and moco loss.


About 5,00 rounds of training:
![image](https://user-images.githubusercontent.com/71555398/163973087-b8e7abe9-6be0-48a1-a407-77b4119f7384.png)

About 10,00 rounds of training:
![image](https://user-images.githubusercontent.com/71555398/163973297-bb279bd6-6f07-4600-8abf-93fd062a8b13.png)

About 10,000 rounds of training:
![image](https://user-images.githubusercontent.com/71555398/163973451-415d4048-1990-4fa8-aa4f-41b1083e6ad9.png)

But in fact my stylegan generator can generate a variety of pictures, but it doesn't show it well during training, what could be the reason?

**Comment by yuval-alaluf** [comment]
What is the relationship between the input images and output images? Is this mapping something that can be learned? I couldn't find a clear mapping between the inputs and outputs in the examples you showed

**Comment by Mo-Irene** [comment]
Maybe that would be the possible reason, I would disable the horizontal flip and try again :)

My input image and output image are images generated by different imaging mechanisms. As you can see, although they contain almost the same semantic features, the target image is much more readable than the input image. Actually they contain different band information of the same target, I am not sure if this causes the encoder to fail to work well. But they are the same in the principle of image storage, and I have tried this kind of image conversion task on other networks before, and the effect does not look bad.
