### ISSUE TITLE
How to make restyle encoder mobile deployment 

### ISSUE THREAD

**Issue by abdul756** [yuval-alaluf/restyle-encoder#71]
The encoder size is around 1.2 GB, due to this the model wouldn't be deployable on Mobile devices. is there any way to make encoder size around 100MB.

**Comment by yuval-alaluf** [comment]
I would start off by checking where most of the model parameters are and then play around with ways to decrease the bottlenecks there. I would then look into trying out different backbones instead of resnet34 and different ways to compress models. 
Deploying these models on mobile is not trivial and will require some training.

**Comment by abdul756** [comment]
Hi Yuval,I am confused with the parameters and in which code I should change I am not getting , I am not getting which parameters to reduce , please  help me

**Comment by yuval-alaluf** [comment]
If you want to reduce the size of the encoder, you need to analyze the number of parameters in the encoder and see where most of the parameters are. You can then try making modifications to the encoder architecture to try to reduce the size. A good starting point would be to try to reduce the parameters in the map2style blocks which hold a decent percentage of the overall network parameters.
The definition of the encoder is defined here so you can analyze the architecture and try to make modifications:
https://github.com/yuval-alaluf/restyle-encoder/blob/main/models/encoders/restyle_psp_encoders.py

**Comment by abdul756** [comment]
Thanks Yuval ,i will get back to you if i have any doubt

**Comment by Ir1d** [comment]
Hi @abdul756 , how was your deployment. Could you please share your results?
