### ISSUE TITLE
After sh train.sh, did someone stay still like me?

### ISSUE THREAD

**Issue by CatDogS** [yuval-alaluf/restyle-encoder#73]
When I `python train_restyle_psp.py` , the console has not reported errors or displayed anything。It lasted for half an hour.

**Comment by CatDogS** [comment]
An hour later, `Ctrl + c ` when I interrupted the process, the display program stuck here.
![image](https://user-images.githubusercontent.com/43256810/167254631-58635f51-1f76-4b60-a80c-1f252f8beeef.png)

**Comment by yuval-alaluf** [comment]
This occurs when there's a deadlock with the compilation of the CUDA extensions related to StyleGAN. 
I believe my comment here will help you: 
https://github.com/eladrich/pixel2style2pixel/issues/80#issuecomment-778637066

**Comment by CatDogS** [comment]
thanks for your help
