### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by JNash123** [yuval-alaluf/restyle-encoder#74]
Sorry to bother u. I learned style mixing and interpolation from u. But I still have problem in image editing.
![image](https://user-images.githubusercontent.com/29653541/174482398-73ccf8c6-fdd7-46be-b281-d60b1124e9c1.png)
The G is StyleGAN2, and the reconstruction results are good. I wanna edit my image by interfacegan.
i saved the latent codes as .npy and ran the following:
python edit.py -m stylegan_ffhq -b boundaries/stylegan_ffhq_age_w_boundary.npy -i LATENT_CODES_FILE.npy -o results/my_image_but_aged -s wp
the result is like this:
![000_000](https://user-images.githubusercontent.com/29653541/174482643-06895221-8399-4e9b-9c7f-07ec59a0ea30.jpg)
if i wanna edit image, what should i do, can u give me more details?Sorry if my question seems stupid

**Comment by yuval-alaluf** [comment]
It seems like you are using the repo for InterFaceGAN? If so, their boundaries are for StyleGAN1, and will therefore not work for you. I provide code for inverting and editing with ReStyle + InterFaceGAN in this repo. Here are the details: 
https://github.com/yuval-alaluf/restyle-encoder#editing

**Comment by JNash123** [comment]
thank u, i'll try
