### ISSUE TITLE
Use Restyle encoder for whole body image inversion

### ISSUE THREAD

**Issue by onyekaokonji** [yuval-alaluf/restyle-encoder#76]
Thanks for this quality work. I will like to know if Restyle can be used for inversion of whole body images and if yes, please share a link.

**Comment by yuval-alaluf** [comment]
ReStyle can be used to invert various domains. You could try using it to invert whole-body images. Unfortunately, I cannot share a link since I haven't tried training one myself, but you are welcome to try training one yourself.

**Comment by onyekaokonji** [comment]
Alright. Thank you!
