### ISSUE TITLE
Question about training StyleGAN

### ISSUE THREAD

**Issue by fxcdl** [yuval-alaluf/restyle-encoder#78]
Hello again.
         I've decided to train your Restyle on my dataset（translation datasets, contained source and target img）. Firstly, I need to train StyleGAN on my domain, but i m very confused that should I need put source and target img together to train the StyleGAN or only use one of them?

         Thanks in advance for the answer.

**Comment by yuval-alaluf** [comment]
Notice that your source and target datasets are identical (since you're trying to solve reconstruction). Therefore, to train your StyleGAN, you only need to define one dataset. This can simply be all your training images.

**Comment by fxcdl** [comment]
Alright. Thanks for the explanations.
