### ISSUE TITLE
Question about training custom sketch data

### ISSUE THREAD

**Issue by YoungNF** [yuval-alaluf/restyle-encoder#81]
Hi, I appreciate your wonderful work.
I have human-drawn sketch images of various furniture and trained restyle-PSP on my own dataset with custom trained StyleGAN2-ADA model.
![image](https://user-images.githubusercontent.com/56923105/199143646-6c8db9dc-8d7b-4bb6-859f-f9c007f37b4c.png)
This is a sample image

Here is my options.
_python scripts/train_restyle_psp.py 
--dataset_type=human_sketch
--encoder_type=ResNetBackboneEncoder 
--exp_dir=002_Mug_1031-1844 
--workers=8 
--batch_size=2 
--test_batch_size=2 
--test_workers=8 
--val_interval=5000 
--save_interval=10000 
--start_from_latent_avg 
--lpips_lambda=0.8 
--l2_lambda=1 
--w_norm_lambda=0.005 
--id_lambda=0 
--moco_lambda=0.5 
--input_nc=6
--n_iters_per_batch=5 
--output_size=512 
--stylegan_weights=sketch2sketch_55_4800.pt 
--checkpoint_path /home/croissantwaffle/restyle-encoder/001_Mug_1031-1620/checkpoints/best_model.pt_

However, the trained model makes some parts well (left handle-view; cylinder-view; round handle) and some parts poorly (right handle-view; isometric-view; angled handle). Other furniture are worse.

![0001_40000](https://user-images.githubusercontent.com/56923105/199142639-312eeeee-5bdb-4ac3-9294-aca885ef8a09.jpg)
![0003_40000](https://user-images.githubusercontent.com/56923105/199142651-4d48c814-4773-440d-83e6-7640d48626bb.jpg)
![0006_40000](https://user-images.githubusercontent.com/56923105/199142666-417adf7a-4bc1-463c-8ddc-52954d8a8b5b.jpg)

Above were trained on **40,000** iterations.

I would really need your help to have improvements.
1) Is the StleGAN2-ADA model not trained enough or is it overfitting?
2) Options set wrong?
3) Limitations on these kind of domains?
4) Do you have any other insights?

Sincerely,

**Comment by yuval-alaluf** [comment]
Regarding your questions: 
1. Did you generate some random samples from your generator and see the quality of the images? If they are of low quality and do not resemble the images in your training set, then ReStyle won't really be able to reconstruct your training images. 
2. The options seem good from what I can tell. These are good starting points. 
3. As for limitations, the main limitation is the quality of the StyleGAN generator - if it can't generator images that resemble those of your real dataset, then ReStyle won't be able to reconstruct them nicely. 
4. I would also recommend trying to overfit on say 20 images. If you still see that ReStyle is unable to do so, then this may also point to the problem being the StyleGAN generator. 
Hope this helps.

**Comment by YoungNF** [comment]
Hello, thank you for your response.
After about a month since I raised the question, I decided to utilize the only ones, such as left-handle views, that are generated well.

Referring to your answers, I should try more efforts on the StyleGAN generator if I want good results from other views as well.

I appreciate your answers, and they helped me a lot.
