### ISSUE TITLE
Question about converting pytorch-ada model.

### ISSUE THREAD

**Issue by zhanjiahui** [yuval-alaluf/restyle-encoder#84]
Thank you for your excellent work! 

​Thus, I can use export_weights.py to convert offical implimation to your .pt format. 
However, export_weights.py only support convert parameters of generator. Could you have any plan about releasing code for convert parameters of discriminter?

**Comment by yuval-alaluf** [comment]
We took the conversion scripts from other repos and therefore have no intention to provide support for converting the parameters of the discriminator. You can possibly open an issue in the original repositories where the code was taken from and ask them there.
