### ISSUE TITLE
Missing optimisation steps

### ISSUE THREAD

**Issue by MISSEY** [yuval-alaluf/restyle-encoder#85]
Hi, I was trying to understand where you perform the optimisation steps after training. I am referring to this in the paper 

"For measuring the optimization technique from [27], we invert the input image using a varying number of steps from 1 optimization step up to 1, 500 steps."

I tried looking into the stylegan2 implementation, but got confuse, as there they are using noise 

https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/projector.py#L57

Could you help me here to create a optimiser for restyle-encoder.

**Comment by yuval-alaluf** [comment]
I think you are mixing up a few things here. With ReStyle, we do not perform any optimization after training. The entire inversion process occurs via the trained encoder.

> "For measuring the optimization technique from [27], we invert the input image using a varying number of steps from 1 optimization step up to 1, 500 steps."

This refers to the comparisons we performed with optimization-based techniques. We took the original implementation of the StyleGAN2 optimization and simply ran the optimization process for up to 1,500 steps.

In this [line](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/projector.py#L70) you can see that they are performing the optimization on the `w_opt` latent, which is initialized to be `w_avg`. 

Does this help answer your question?

**Comment by MISSEY** [comment]
@yuval-alaluf , thank you so much for your answer. So I just pass the latent code from restyle in the place of w_avg ? But the size of codes are N,18,512 and the w_avg is of size 1,512. In this projector.py they are just averaging over 10k w_avg samples and have size 1,512. Should I also just average over 18 to create 1,512 for latent code of restyle ? 

Thanks again

**Comment by yuval-alaluf** [comment]
I think you are mixing up some concepts here. ReStyle and the optimization you are referring to are two separate things entirely. 
The output of ReStyle is not passed to the optimization process in our comparisons. You could do this if you want, but we did not do this in our paper. 
Typically, when performing optimization, the vector w_avg is still 18x512 (i.e. in W+) so the sizes are the same. In the code you presented, I am not sure whether they perform it using a W vector (of size 1x512) or a W+ vector (of size 18x512), but if you want the best results, you'll want to make the vector be in W+. 
Hope this helps clarify some of the points.
