### ISSUE TITLE
failed to run colab notebook

### ISSUE THREAD

**Issue by Mustafa744** [yuval-alaluf/restyle-encoder#9]
Downloading ReStyle model for toonify...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-020a950dcfbe> in <module>()
      4     # if google drive receives too many requests, we'll reach the quota limit and be unable to download the model
      5     if os.path.getsize(EXPERIMENT_ARGS['model_path']) < 1000000:
----> 6         raise ValueError("Pretrained model was unable to be downloaded correctly!")
      7     else:
      8         print('Done.')

ValueError: Pretrained model was unable to be downloaded correctly!

**Comment by yuval-alaluf** [comment]
It seems like we reached the quota limit for downloading the pretrained model. You should try again in a bit (an hour or so). 
You can also try using `gdown` which may be more stable.

**Comment by skylum1** [comment]
NO, there is some problem in data downloading code , I manually copied the URL and was able to download from URL , so I copied the model into my drive and then added it by connecting my drive.  I believe the downloading command is working asynchronously so before download completes it  triggers the  size condition and throws the error.

**Comment by yuval-alaluf** [comment]
@skylum1 , I am not too sure that the downloading command is asynchronous. According to the docs, `os.systems()` will force python to wait until the process has completed before continuing the execution. In this case, the download must finish before moving on to check that the size is valid. 
In any case, I just ran the colab notebook and was able to download the `churches` model with no issues. 
Another easy way to check that the model was downloaded correctly is that if you see that the model is, say, 3kB, you can run `cat` on it and check if you see the quota warning. 
Can you please check again that this is indeed caused by what you mentioned? If the issue persists I will look into it again.

**Comment by ash2703** [comment]
**gdown** works great for me

```
pip install gdown
!gdown https://drive.google.com/uc?id=file_id
```

You can get the file id from `download_command`

**Comment by Mustafa744** [comment]
why to use os.system()?
couldn't it just be replace by adding ! wget ?

**Comment by yuval-alaluf** [comment]
@Mustafa744 - yea that's definitely possible. I chose to use `os.system` because that way I could do everything in python. By doing so, I was able to add the check `if not os.path.exists(EXPERIMENT_ARGS['model_path'])` thereby ensuring that the model was only downloaded once (reduce the number of requests to the drive).
There are probably nicer ways to do so that I am not aware of :)

**Comment by ash2703** [comment]
Prefer using pathlib in that case, handling files is much more simplified

**Comment by Mustafa744** [comment]
@yuval-alaluf  i hate the os module 🤣
will you update the colab notebook with this edit ?

**Comment by japrogramer** [comment]
I can't download the pretrained model

> !pip install gdown
> !gdown https://drive.google.com/uc?id=1sw6I2lRIB0MpuJkpc8F5BJiSZrc0hjfE

Requirement already satisfied: gdown in /usr/local/lib/python3.7/dist-packages (3.6.4)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from gdown) (1.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from gdown) (2.23.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from gdown) (4.41.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (2020.12.5)
Permission denied: https://drive.google.com/uc?id=1sw6I2lRIB0MpuJkpc8F5BJiSZrc0hjfE
Maybe you need to change permission over 'Anyone with the link'?

**Comment by yuval-alaluf** [comment]
> @yuval-alaluf i hate the os module 🤣
> will you update the colab notebook with this edit ?

@Mustafa744 - since the current method does work when there are no issues with the quota, I do not plan on making any changes. However, if you feel like there are improvements that can be made you are welcome to open a pull request with these changes.

**Comment by yuval-alaluf** [comment]
> I can't download the pretrained model
> 
> > !pip install gdown
> > !gdown https://drive.google.com/uc?id=1sw6I2lRIB0MpuJkpc8F5BJiSZrc0hjfE
> 
> Requirement already satisfied: gdown in /usr/local/lib/python3.7/dist-packages (3.6.4)
> Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from gdown) (1.15.0)
> Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from gdown) (2.23.0)
> Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from gdown) (4.41.1)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (2.10)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (1.24.3)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->gdown) (2020.12.5)
> Permission denied: https://drive.google.com/uc?id=1sw6I2lRIB0MpuJkpc8F5BJiSZrc0hjfE
> Maybe you need to change permission over 'Anyone with the link'?
> 
> All the other methods to download the pretrained model also fail as described in this issue.
> However I can download the file links manually .. too tedious tho.

I have examined this further. All the models I linked here have the correct permissions. Based on this issue, https://github.com/wkentaro/gdown/issues/43, it appears that this is yet again an issue with reaching the quota on Google Drive. 
I was able to use `gdown --id <file id>` to download a select number of files, however, 
Unfortunately, there is not much I can do at this time. It just happened that many people have tried downloading the models in the past 24 hours. I kindly ask everyone to be patient to see if this issue resolves itself in the next day or two. Thanks.
